apiVersion: apps/v1
kind: Deployment
metadata:
  name: binit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binit
  template:
    metadata:
      labels:
        app: binit
    spec:
      containers:
        - name: binit-container
          image: nginx:latest
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: binit-admin-secret
