apiVersion: apps/v1
kind: Deployment
metadata:
  name: binit-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: binit
  template:
    metadata:
      labels:
        app: binit
    spec:
      containers:
      - name: binit-container
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: ADMIN_ID
          valueFrom:
            secretKeyRef:
              name: binit-admin-secret
              key: ADMIN_ID
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: binit-admin-secret
              key: ADMIN_PASSWORD
        - name: ADMIN_URL
          valueFrom:
            secretKeyRef:
              name: binit-admin-secret
              key: ADMIN_URL
